version: '3.9'

services:
  kavita:
    image: kizaing/kavita:latest
    networks:
      - network
    environment:
      - TZ=US/East-Indiana
    volumes:
      - /mnt/media/books:/manga
      - /mnt/docker-data/kavita/config:/kavita/config
    restart: unless-stopped

networks:
  network:
    driver: bridge