version: '3.9'

services:
  speedtest:
    image: henrywhitaker3/speedtest-tracker
    network_mode: bridge
    expose:
      - 80
    environment:
      - OOKLA_EULA_GDPR=true
    volumes:
        - speedtest-volume:/config
    restart: unless-stopped
  arm:
    image: automaticrippingmachine/automatic-ripping-machine:latest
    network_mode: bridge
    expose:
      - 8080
    environment:
      - ARM_UID=${ARM_UID}
      - ARM_GID=${ARM_GID}
      - MAKEMKV_APP_KEY=${MAKEMKV_APP_KEY}
    volumes:
      - /mnt/media/arm:/home/arm
      - /mnt/media/arm/Music:/home/arm/Music
      - /mnt/media/arm/logs:/home/arm/logs
      - /mnt/media/arm/media:/home/arm/media
      - /mnt/media/arm/config:/etc/arm/config
      - /mnt/media/arm/db:/home/arm/db
    devices:
      - /dev/sr0:/dev/sr0
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "9.0"
          memory: "4096M"  
    restart: unless-stopped
  pyload:
    image: mobilistics/pyload:latest
    network_mode: bridge
    expose:
      - 8000
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - pyload_volume:/opt/pyload/pyload-config
      - /mnt/media/roms/Downloads:/opt/pyload/Downloads
    labels:
      - traefik.http.services.pyload.loadbalancer.server.port=8000
    restart: unless-stopped

volumes:
  speedtest-volume:
    external: true
  pyload_volume:
