version: '3.9'

services:
  sqlfts:
    image: jd/mssql-fts:ubuntu
    container_name: sql-fts
    network_mode: bridge
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=true
      - SA_PASSWORD=${SQL_SA_PASSWORD}
    volumes:
      - ${SQL_DATA_FOLDER}:/var/opt/mssql/data
    labels:
      - traefik.enable=false
    restart: unless-stopped
  arm:
    image: automaticrippingmachine/automatic-ripping-machine:latest
    container_name: arm-rippers
    network_mode: bridge
    ports: 
      - "8100:8080"
    environment:
      - ARM_UID=${ARM_UID}
      - ARM_GID=${ARM_GID}
      - MAKEMKV_APP_KEY=${MAKEMKV_APP_KEY}
    volumes:
      - /mnt/media/arm:/home/arm
      - /mnt/media/arm/Music:/home/arm/Music
      - /mnt/media/arm/logs:/home/arm/logs
      - /mnt/media/arm/media:/home/arm/media
      - /mnt/media/arm/config:/etc/arm/config
      - /mnt/media/arm/db:/home/arm/db
    devices:
      - /dev/sr0:/dev/sr0
    privileged: true
    restart: unless-stopped
    cpus: 0.75
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    container_name: traefik
    network_mode: host
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml
    restart: unless-stopped
