version: '3.9'

services:
  speedtest:
    image: henrywhitaker3/speedtest-tracker
    network_mode: bridge
    expose:
      - 80
    environment:
      - OOKLA_EULA_GDPR=true
    volumes:
        - speedtest-volume:/config
    restart: unless-stopped
  kavita:
    image: kizaing/kavita:latest
    network_mode: bridge
    expose:
      - 5000
    environment:
      - TZ=US/East-Indiana
    volumes:
      - /mnt/media/books:/manga
      - /mnt/media/kavita:/kavita/config
    restart: unless-stopped
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    network_mode: bridge
    expose:
      - 80
    volumes:
      - /mnt/media/audiobookshelf/audiobooks:/audiobooks
      - /mnt/media/audiobookshelf/podcasts:/podcasts
      - /mnt/media/audiobookshelf/config:/config
      - /mnt/media/audiobookshelf/metadata:/metadata
    restart: unless-stopped
  arm:
    image: automaticrippingmachine/automatic-ripping-machine:latest
    network_mode: bridge
    expose:
      - 8080
    environment:
      - ARM_UID=${ARM_UID}
      - ARM_GID=${ARM_GID}
      - MAKEMKV_APP_KEY=${MAKEMKV_APP_KEY}
    volumes:
      - /mnt/media/arm:/home/arm
      - /mnt/media/arm/Music:/home/arm/Music
      - /mnt/media/arm/logs:/home/arm/logs
      - /mnt/media/arm/media:/home/arm/media
      - /mnt/media/arm/config:/etc/arm/config
      - /mnt/media/arm/db:/home/arm/db
    devices:
      - /dev/sr0:/dev/sr0
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "9.0"
          memory: "4096M"  
    restart: unless-stopped
  pyload:
    image: mobilistics/pyload:latest
    network_mode: bridge
    expose:
      - 8000
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - pyload_volume:/opt/pyload/pyload-config
      - /mnt/media/roms/Downloads:/opt/pyload/Downloads
    labels:
      - traefik.http.services.pyload.loadbalancer.server.port=8000
    restart: unless-stopped
  bookstack:
    image: lscr.io/linuxserver/bookstack
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.${HOST}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${BOOKSTACK_DB_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/media/bookstack/config:/config
    expose:
      - 80
    links:
      - "bookstack-db:db"
    restart: unless-stopped
    depends_on:
      - bookstack-db
  bookstack-db:
    image: lscr.io/linuxserver/mariadb
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_DB_ROOT_PASSWORD}
      - TZ=Etc/UTC
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASSWORD}
    volumes:
      - /mnt/media/bookstack/mariadb/config:/config
    labels:
      - traefik.enable=false
    restart: unless-stopped
  plex:
    image: plexinc/pms-docker:1.32.2.7100-248a2daf0
    network_mode: host
    # ports:
    #   - 32400:32400/tcp
    #   - 3005:3005/tcp
    #   - 8324:8324/tcp
    #   - 32469:32469/tcp
    #   - 1900:1900/udp
    #   - 32410:32410/udp
    #   - 32412:32412/udp
    #   - 32413:32413/udp
    #   - 32414:32414/udp
    environment:
      - TZ=America/Indiana/Indianapolis
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://${ADVERTISE_IP}:32400/
    volumes:
      - /mnt/media/plex/database:/config
      - /mnt/media/plex/transcode:/transcode
      - /mnt/media/plex/media:/data
    restart: unless-stopped
    labels:
      - traefik.http.services.plex.loadbalancer.server.port=32400
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    network_mode: bridge
    expose:
      - 80
      - 3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/media/emulatorjs/config:/config
      - /mnt/media/emulatorjs/data:/data
      - /mnt/media/roms/roms/nes:/data/nes/roms
      - /mnt/media/roms/roms/snes:/data/snes/roms
      - /mnt/media/roms/roms/gba:/data/gba/roms
      - /mnt/media/roms/roms/gb:/data/gb/roms
      - /mnt/media/roms/roms/gbc:/data/gbc/roms
      - /mnt/media/roms/roms/n64:/data/n64/roms
      - /mnt/media/roms/roms/nds:/data/nds/roms
      - /mnt/media/roms/roms/psx:/data/psx/roms
    labels:
      - traefik.http.routers.emulatorjs.entryPoints=websecure
      - traefik.http.routers.emulatorjs.service=emulatorjs
      - traefik.http.services.emulatorjs.loadbalancer.server.port=80
      - traefik.http.routers.admin-emulatorjs.entryPoints=websecure
      - traefik.http.routers.admin-emulatorjs.rule=Host(`admin-emulatorjs.${HOST}`)
      - traefik.http.routers.admin-emulatorjs.service=admin-emulatorjs
      - traefik.http.services.admin-emulatorjs.loadbalancer.server.port=3000
    restart: unless-stopped
  traefik:
    image: traefik/traefik:experimental-master
    network_mode: host
    environment:
      - HOST=$HOST
      - CERT_NAME=$CERT_NAME
      - JSON_SERVICES=$JSON_SERVICES
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.http.tls=true"
      - "--entryPoints.websecure.asDefault=true"
      - "--entryPoints.gitea-ssh.address=:222/tcp"
      - "--entryPoints.mssql.address=:1433"
      # https://doc.traefik.io/traefik/master/providers/docker/#defaultrule
      - "--providers.docker.defaultRule=Host(`{{if index .Labels \"com.docker.compose.service\" }}{{ index .Labels \"com.docker.compose.service\" }}{{else}}{{ trimPrefix `/` .Name }}{{end}}.${HOST}`)"
      # docker labels don't seem to work correctly once you add dynamic config
      - "--providers.file.directory=/conf"
      - "--providers.file.watch=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik:/conf:ro
      - ./certs:/certs:ro
    restart: unless-stopped

volumes:
  speedtest-volume:
    external: true
  jdownloader2_volume:
  pyload_volume:
