version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    network_mode: "host"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/media/traefik/traefik.yml:/etc/traefik/traefik.yml
    restart: unless-stopped
