version: "3.7"
services:
  mealie:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    networks:
      - network
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 # 
    # ports:
    #   - "9925:3000" # 
    depends_on:
      - mealie-api
    volumes:
      - /mnt/docker-data/mealie/data:/app/data/ # 
    restart: unless-stopped

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    networks:
      - network
    deploy:
      resources:
        limits:
          memory: 1000M # 
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.${HOST}
    labels:
      - traefik.enable=false
    volumes:
      - /mnt/docker-data/mealie/data:/app/data/
    restart: unless-stopped

networks:
  network:
    driver: bridge
