version: '3.9'

services:
  plex:
    image: plexinc/pms-docker:1.32.2.7100-248a2daf0
    network_mode: host
    # ports:
    #   - 32400:32400/tcp
    #   - 3005:3005/tcp
    #   - 8324:8324/tcp
    #   - 32469:32469/tcp
    #   - 1900:1900/udp
    #   - 32410:32410/udp
    #   - 32412:32412/udp
    #   - 32413:32413/udp
    #   - 32414:32414/udp
    environment:
      - TZ=America/Indiana/Indianapolis
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://${ADVERTISE_IP}:32400/
    volumes:
      - /mnt/docker-data/plex/database:/config
      - /mnt/docker-data/plex/transcode:/transcode
      - /mnt/media/videos:/data
    restart: unless-stopped
    labels:
      - traefik.http.services.plex.loadbalancer.server.port=32400
