version: '3.9'

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    networks:
      - network
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://bookstack.${HOST}
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=${BOOKSTACK_DB_PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - /mnt/docker-data/bookstack/config:/config
    restart: unless-stopped
    depends_on:
      - bookstack-db
  bookstack-db:
    image: lscr.io/linuxserver/mariadb
    networks:
      - network
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_DB_ROOT_PASSWORD}
      - TZ=Etc/UTC
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASSWORD}
    volumes:
      - /mnt/docker-data/bookstack/mariadb/config:/config
    labels:
      - traefik.enable=false
    restart: unless-stopped

networks:
  network:
    driver: bridge