version: '3.9'

services: 
  sqlfts:
    image: jd/mssql-fts:ubuntu
    network_mode: bridge
    expose:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=true
      - SA_PASSWORD=${SQL_SA_PASSWORD}
    volumes:
      - ${SQL_DATA_FOLDER}:/var/opt/mssql/data
    labels:
      - traefik.tcp.routers.mssql.entryPoints=mssql
      - traefik.tcp.routers.mssql.service=mssql
      - traefik.tcp.routers.mssql.rule=HostSNI(`*`)
      - traefik.tcp.services.mssql.loadbalancer.server.port=1433
    restart: unless-stopped
  gitea:
    image: gitea/gitea:1.19.0
    network_mode: bridge
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${GITEA_USER}
      - GITEA__database__PASSWD=${GITEA_PASSWORD}
    volumes:
      - /mnt/media/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 22
      - 3000
    labels:
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.tcp.routers.gitea-ssh.entryPoints=gitea-ssh
      - traefik.tcp.routers.gitea-ssh.service=gitea-ssh
      - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
      - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22
    depends_on:
      - gitea-db
    links:
      - "gitea-db:db"
    restart: unless-stopped
  gitea-db:
    image: postgres:14
    network_mode: bridge
    environment:
      - POSTGRES_USER=${GITEA_USER}
      - POSTGRES_PASSWORD=${GITEA_PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - /mnt/media/gitea/postgres/data:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    restart: unless-stopped