version: '3.9'

services: 
  sqlfts:
    image: jd/mssql-fts:ubuntu
    network_mode: bridge
    expose:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=true
      - SA_PASSWORD=${SQL_SA_PASSWORD}
    volumes:
      - ${SQL_DATA_FOLDER}:/var/opt/mssql/data
    labels:
      - traefik.tcp.routers.mssql.entryPoints=mssql
      - traefik.tcp.routers.mssql.service=mssql
      - traefik.tcp.routers.mssql.rule=HostSNI(`*`)
      - traefik.tcp.services.mssql.loadbalancer.server.port=1433
    deploy:
      resources:
        limits:
          memory: "4000M"  
    restart: unless-stopped
  