version: "3.7"
services:
  mealie:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    network_mode: bridge
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://api:9000 # 
    # ports:
    #   - "9925:3000" # 
    links:
      - "mealie-api:api"
    depends_on:
      - mealie-api
    restart: unless-stopped
    volumes:
      - /mnt/media/mealie/data:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - /mnt/media/mealie/data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.${HOST}
    labels:
      - traefik.enable=false
    restart: unless-stopped
