version: '3.9'

services:
  gitea:
    image: gitea/gitea:1.21.11
    networks:
      - network
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${GITEA_USER}
      - GITEA__database__PASSWD=${GITEA_PASSWORD}
    volumes:
      - /mnt/docker-data/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.tcp.routers.gitea-ssh.entryPoints=gitea-ssh
      - traefik.tcp.routers.gitea-ssh.service=gitea-ssh
      - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
      - traefik.tcp.services.gitea-ssh.loadbalancer.server.port=22
    depends_on:
      - gitea-db
    restart: unless-stopped
  gitea-db:
    image: postgres:14
    networks:
      - network
    environment:
      - POSTGRES_USER=${GITEA_USER}
      - POSTGRES_PASSWORD=${GITEA_PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - /mnt/docker-data/gitea/postgres/data:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    restart: unless-stopped
  runner:
    image: gitea/act_runner:0.2.8
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: ${INSTANCE_URL}
      GITEA_RUNNER_REGISTRATION_TOKEN: ${REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: ${RUNNER_NAME}
    networks:
      - network
    volumes:
      - ./config/gitea-runner/config.yaml:/config.yaml
      - /mnt/docker-data/gitea/gitea-runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ../certs/rootCA.crt:/etc/ssl/certs/rootCA.crt:ro
    depends_on:
      - gitea
    restart: unless-stopped

networks:
  network:
    driver: bridge
