version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    command: start --optimized --proxy edge
    environment:
      VIRTUAL_HOST: >-
        keycloak.${HOST}
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: keycloak.${HOST}
    depends_on:
      - postgres
    labels:
      - traefik.frontend.passHostHeader=true
    restart: unless-stopped
    networks:
      - network

  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    restart: unless-stopped
    volumes:
      - /mnt/docker-data/keycloak/postgres/data:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    networks:
      - network

networks:
  network:
    driver: bridge
