version: '3.9'

services:  
  ca-cert:
    image: nginx:latest
    networks:
      - network
    volumes:
      - ${ROOT_CA}:/usr/share/nginx/html/rootCA.pem:ro
    labels: 
      - traefik.http.routers.ca-cert.entryPoints=web
    restart: unless-stopped

networks:
  network:
    driver: bridge