version: '3'

services:
  api:
    image: registry:2
    restart: unless-stopped
    # ports:
    # - "5000:5000"
    volumes:
      - /mnt/docker-data/borkerhub/registry:/var/lib/registry
    labels:
      - traefik.http.services.conreg.loadbalancer.server.port=5000
      - traefik.http.routers.conreg.service=conreg
      - traefik.http.routers.conreg.rule=Host(`borkerhub.${HOST}`)
    networks:
      - network

  ui:
    image: konradkleine/docker-registry-frontend:v2
    restart: unless-stopped
    # ports:
    #   - "8080:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: api
      ENV_DOCKER_REGISTRY_PORT: 5000
    depends_on:
      - api
    labels:
      - traefik.http.services.conreg-ui.loadbalancer.server.port=80
      - traefik.http.routers.conreg-ui.service=conreg-ui
      - traefik.http.routers.conreg-ui.rule=Host(`borkerhubui.${HOST}`)
    networks:
      - network

networks:
  network:
