# traefik dynamic configuration

## traefik dashboard config
http:
  routers:
    websecure-dashboard:
      rule: Host(`traefik.{{env "HOST"}}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      entrypoints: websecure
      service: api@internal
      middlewares:
        - auth
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$2y$05$0ClyV/pLw0RulnLnb6KvceR9h9TKqLuZmzv4nYAOHL2x/dW97hy9K"

# This is the old config that served up a wildcard *.{HOST} certificate. Not needed with ACME.
## TLS certs
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /certs/{{env "CERT_NAME"}}.crt
#         keyFile: /certs/{{env "CERT_NAME"}}.key