version: '3.9'

services:  
  dozzle:
    image: amir20/dozzle:latest
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  network:
    driver: bridge